sonar.host.url=https://sonar-server.tiket.com
# must be unique in a given SonarQube instance
sonar.projectKey=angga-kesuma
sonar.projectVersion=1.0.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=.
sonar.sources.inclusions=**/**.go
sonar.inclusions=plugin/**/*.go
sonar.exclusions=plugin/http-client/middleware/*.go

sonar.tests=./
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=*.*,conf/**/*.*

# sonar.go.gometalinter.reportPaths=cicd/sonarqube-report/gometalinter-report.out
# sonar.go.tests.reportPaths=**.json
sonar.go.coverage.reportPaths=plugin/coverage.out
# sonar.go.gometalinter.reportPaths=gometalinter-report.out
sonar.go.coverage.dtdVerification=false

# sonar.showProfiling=true
# sonar.log.level=DEBUG
